### PR TITLE
Add list of related specifications to top of document.

### PR DESCRIPTION
**Pull request by msporny**
This PR adds a list of related specifications to the top of the EdDSA Cryptosuites specification.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-eddsa/pull/48.html" title="Last updated on Jul 6, 2023, 11:22 AM UTC (2cefc21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-eddsa/48/5013e42...2cefc21.html" title="Last updated on Jul 6, 2023, 11:22 AM UTC (2cefc21)">Diff</a>

### CODE REVIEW

**Review by iherman — APPROVED** [review]
I think this is a great idea, and I also see that there is similar PR for ecdsa. Will do this systematically for all the others? (BBS, JWT, etc)? I think we should...

**Review by Wind4Greg — APPROVED** [review]
Nice editorial enhancement.

**Review by pchampin — APPROVED** [review]

**Review by TallTed — APPROVED** [review]
lgtm

**Review by dlongley — APPROVED** [review]

**Review by brentzundel — APPROVED** [review]

**Comment by msporny** [comment]
>  Will do this systematically for all the others? (BBS, JWT, etc)? I think we should...

Yes, that would probably be a good idea, but I leave it to the Editor's of those documents to do the PRs.

**Comment by TallTed** [comment]
> Yes, that would probably be a good idea, but I leave it to the Editor's of those documents to do the PRs.

Probably worthwhile to at least tag them here, if not create issues on each?

**Comment by msporny** [comment]
Editorial, multiple positive reviews, no changes requested, no objections, merging.

**Pull request merged**
