### PR TITLE
Fix B.3 Representation: Ed25519Signature2020 test vectors

### PR DESCRIPTION
**Pull request by filip26**
Adds missing `@context` `https://w3id.org/security/suites/ed25519-2020/v1`  to `Ed25519Signature2020` test vectors.  Proof canonical form, hash, and signature are re-computed.

It's related to, but does not close, issue #75

***
<a href="https://pr-preview.s3.amazonaws.com/filip26/vc-di-eddsa/pull/76.html" title="Last updated on Feb 27, 2024, 5:41 PM UTC (52110f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-eddsa/76/215cdba...filip26:52110f6.html" title="Last updated on Feb 27, 2024, 5:41 PM UTC (52110f6)">Diff</a>

### CODE REVIEW

**Comment by msporny** [comment]
@filip26, thanks for the PR -- do you know if these updates align w/ other implementations (I imagine they do since you're passing the test suite?)

@Wind4Greg, what's going on with these test vectors? Are these updates correct?

**Comment by filip26** [comment]
@msporny Without a proper `Ed25519Signature2020` context, the proof is expanded with using of example context, e.g. `https://www.w3.org/ns/credentials/examples#Ed25519Signature202` instead of `https://w3id.org/security#Ed25519Signature2020`. This PR fixes that. 

I expect no issues for other implementations, on the contrary, without the right context, the result using example context is not verifiable, i.e. a proof type is unknown to a verifier.

**Comment by Wind4Greg** [comment]
Thanks @filip26 and @msporny! Let me update my test vector code and see if I  can confirm. Cheers Greg

**Review by Wind4Greg — APPROVED** [review]
Verified these against my vectors. Thanks @filip26!

**Review by dlongley — APPROVED** [review]
Thanks! This looks like what I asked for in #75. I haven't checked this against our implementation but it definitely looks better.

**Review by msporny — APPROVED** [review]

**Pull request merged**
